### ISSUE TITLE
Cell-free Protein Translation Assay for OSM-S-106

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series3#15]
@StuartRalph suggested in OpenSourceMalaria/Series3#12 that we test the mechanism of action of OSM-S-106 using a protein translation assay. I caught up with him in Melbourne and he further suggested the use of a [recently-published assay from Joe Derisi involving a cell-free translation assay](https://www.ncbi.nlm.nih.gov/pubmed/30541569). I wrote to Joe, who replied:

"We would be happy to run your compound in our assay. We routinely run it, so not a problem. In fact, we make so much extract, we [built a little robot to crank out the stuff](https://doi.org/10.1016/j.ohx.2018.e00027)." The student running the assay kindly confirmed they were happy to run our compound and asked:

"It would be great if you could suggest some controls to run alongside it that also target the same synthetase, in PF or generally in eukaryotes, or at least a small panel of controls against various tRNA synthetaseses." i.e. to benchmark this fairly new target class.

I don't think we have any such positive control compounds. Stuart, or maybe @rafacounago could advise?

@mbhebhe we're going to need a sample of OSM-S-106 and the usual negative control shipped to UCSF. I'll get quantities and addresses by email.

**Comment by rafacounago** [comment]
@mattodd - is there a transition state analog you could use as a positive control?

**Comment by mattodd** [comment]
I wish, @rafacounago. I was hoping that we might have exemplified/validated tRNA synthetase inhibitors from other projects. Pinging @sottilie about this possibility.

**Comment by rafacounago** [comment]
Hi @mattodd  - borrelidin and cladosporin, target ThrRS and LysR, respectively, But I am not aware of an inhibitor for our target.

**Comment by StuartRalph** [comment]
There are a bunch of tRNA synthetase inhibitors of Plasmodium that I think should work in Joe's cell free assay. We would want readily-available compounds that inhibit cytosolic, rather than apicoplast enzymes. **Indeed, in their initial validation of the assay, Joe's lab already used halofuginone, an inhibitor of the _Plasmodium_ cytoplasmic Prolyl-tRNA sythetase**. I assume they would have more of this compound and could run that alongside  OSM-S-106.
If we wanted additional controls, as @rafacounago says, both cladosporin [PMID: 22704625] and  borrelidin [PMID: 14563165] should work, (although borrelidin hits a dual-targeted cytosolic/apicoplast enzyme, so has some extra complexity). Thiaisoleucine is another option, which targets the cytoplasmic IleRS [PMID: 21205898]. Inhibitors of apicoplast tRNA synthetases should be reasonable negative controls, and Joe's lab demonstrated other inhibitors of apicoplast  translation (like thiostrepton) were negatives in their assay, so we could add more of these, like the apicoplast-ileRS-inhibitor indolmycin) but my feeling is that this is not necessary.

**Comment by mbhebhe** [comment]
I just sent OSM-S-106 and OSM-S-137 to UCSF (Joe Derisi) for protein translation assay

**Comment by MFernflower** [comment]
Great stuff everyone! Pretty cool how we someone who is somewhat of a celebrity involved

**Comment by mbhebhe** [comment]
We recently received preliminary data
(https://github.com/OpenSourceMalaria/Series3/files/3013740/Preliminary.data.zip)
 from the Derisi lab. Current results are a one off.

The assays are being done by his student and this is what they said
"I ran OSM-S-106 and OSM-S-137 in our IVT assay and unfortunately I did not see any inhibition in our assay. The protein we code for only is 5.8% asparagine and we really don’t know how much of any tRNA-syntase activity is actually occurring since we haven’t really tested any known tRNA-syntase inhibitors.

The raw data is attached along with a visual with the [] plotted as the log[concentration]. 
Lanes A-C were 106 and lanes D-G were 137 at decreasing concentrations from 1-10 (10 being DMSO only for both drugs)." 
[Preliminary data.zip](https://github.com/OpenSourceMalaria/Series3/files/3013741/Preliminary.data.zip)


The following is what they are planning on doing next:
Halofuginone works in our IVT assay at 100x the drug’s EC50, which is equivalent to the highest concentration of 106 used here. Proline composes 5.3% of the protein so its surprisingly similar to the levels of ASN in the protein.
What is worth doing again is testing the drug at 10x, 100x, 500x, 1000x the EC50, which is more like what we did for halofuginone. Then I could also run the equivalent concentrations of 137, halofuginone, and cycloheximide. I think I can also tighten up the data a bit and look at percent inhibition as opposed to total signal in future experiments.

**Comment by mbhebhe** [comment]
More data from the Derisi Lab. 

"I ran the assay for OSM_S_106 at 10, 100, 500, and 1000 fold above the IC50. You start to see inhibition at 500 fold above. That is a lot of compound so it’s hard to know what is happening. We have tested some compounds at those relative levels before that do not inhibit translation at all, but I believe there are others that target apicoplast translation that will start to inhibit at that high of a level, most likely do to off target effects. 
I was not able to run the negative control at the same levels because I made up the whole 1mg of compound in DMSO when I received it and the assay does not work at the required volume of compound to achieve 500 or 1000 fold above. 

I decided to use CHX as a positive control because we’ve used it extensively and we know it targets 80S translation which clearly is a robust/required part of our IVT system. 

The assay in duplicate. This is done with 2.5% final DMSO concentration. For our previous paper we repeated the duplicates 3x"

Data is on here:
https://au-mynotebook.labarchives.com/share/Tha%2520OSM%2520Series%25203/NTM4LjJ8MjcwNjkvNDE0LTE5NTIvVHJlZU5vZGUvNTExOTg2MzQzfDEzNjYuMTk5OTk5OTk5OTk5OA==

https://au-mynotebook.labarchives.com/share/Tha%2520OSM%2520Series%25203/NTM4LjJ8MjcwNjkvNDE0LTE5NTMvVHJlZU5vZGUvMTg1MDE0NjUzOHwxMzY2LjE5OTk5OTk5OTk5OTg=

**Comment by mattodd** [comment]
Closing. This page is linked to on the [wiki](https://github.com/OpenSourceMalaria/Series3/wiki/Mechanism-of-Action). The negative result here is made less important by the positive result of a subsequent in-cell assay, to be included here shortly.
