### ISSUE TITLE
Lab book for synthesis

### ISSUE THREAD

**Issue by JamesAustinJA** [OpenSourceMalaria/Series3#34]
## Desire to help synthesise
Hi, I'm a synthetic chemist working in industry and we have a plan to help out with some synthesis from September as a project for a placement student for about half a year (starting in Sept 2024). I was hoping to help out with some synthesis before they begin to get to grips with how the project works before they start. Would anyone be able to help with getting an online notebook to document synthesis?

# Targets
It does seem that there are a few unmade compounds in the [Other possible molecules of interest] (https://github.com/OpenSourceMalaria/Series3/wiki/Desirable-Compounds-Not-Yet-Synthesised) section to be made that I'd love to help out with. 

Any help with getting started would be much appreciated!

**Comment by mattodd** [comment]
Hey @JamesAustinJA thanks so much for writing! I very much owed you an email, but great you posted here instead. Nice to reconnect.

So - first things first. If you want to contribute to this series (OSM3) then we (me and @yinuowang0812) can highlight what's needed. On my to do list is to update this whole wiki with the new results in the [preprint](https://www.researchsquare.com/article/rs-3198291/v1), and the reason why there is more in the preprint than is on this Github site. Short story: @yinuowang0812 has a target list and we can use that to formulate a target that might be suitable and can tweak that target depending on who's doing the work, so that it's achievable. All good.

If you're not wedded to OSM3, there are other possibilities that might also be of interest (e.g. [these](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/wiki/Desirable-Compounds-Not-Yet-Synthesised), formulated by @EveCarter vs a protein called ABHD2), but let us know your preferences and we can take this further.

Lab notebook - no problem, we can provide an ELN on Labarchives, which is nice to use. Though I should mention @qxsml [has been using Github comments (like the one you're looking at) as a neat low-tech ELN](https://github.com/StructuralGenomicsConsortium/CNP16-iminoquinone-SarsRdRp-mechanstic-study/issues)!

**Comment by JamesAustinJA** [comment]
Hi @mattodd thanks for getting back to me, hope you had a great holiday period.

I think contributing to this series would be the best start. I've had a look at the ABHD2 page and it looks great and there might be something we could help with later on in the year, I'll check in with @EveCarter when I know more. 

If possible I'd like to start with the ELN on labarchives so I can best simulate what our student will do when they start in September.

**Comment by JamesAustinJA** [comment]
@mattodd @yinuowang0812 any update on some sort of target list? 

For the next few months it would just be me helping out with some synthesis so I can get to grips with the project and the reactions before we have an undergrad starting on this in September.

**Comment by mattodd** [comment]
Hi @JamesAustinJA - sounds really great. @yinuowang0812 and I caught up in lab yesterday and will come back to you in a day or so with a menu of current needs.

**Comment by yinuowang0812** [comment]
Hi @JamesAustinJA  thanks for helping out with some chemistry. I've put the notes from our catch-up yesterday, and @mattodd feel free to add anything if I've missed something.

For the current OSM3 project, we have a series of target compounds, and we are particularly interested in seeing how these compounds can affect the geometry of the binding site. The compounds listed below are feasible to synthesise, and our previous master's student had synthesised some intermediates. We will upload her electronic lab notebook (ELN) to the [wiki](https://github.com/OpenSourceMalaria/Series3/wiki/Sources-of-Data) page soon.

<img width="700" alt="Screenshot 2024-01-31 at 10 14 50" src="https://github.com/OpenSourceMalaria/Series3/assets/102600515/94a73d66-3c70-4a08-aed4-c9754062dbc1">

Besides synthesising novel molecules, we are also exploring methodological optimisations for OSM-S-106 analogues. The diagram below is the current synthetic route for our most efficacious OSM3 molecule, OSM-S-106. Typically, we couple bromo-thienopyrimidine 4 with another boronate adduct. This final Suzuki coupling step usually achieves an average yield of around 60%, so we plan to retain it. Our current strategy involves borylating the more readily synthesised thienopyrimidine 4 before further coupling it with additional Br-adducts. I've tested some borylation conditions with Pd, but all attempts have resulted in dehalogenation, a known side reaction with Pd catalysts [[1](https://pubs.rsc.org/en/content/articlehtml/2013/cc/c3cc46271d)] [[2](https://pubs.acs.org/doi/full/10.1021/acs.joc.9b01350)]. I think some sulutions will be either 1) conduct metal catalyst screens, 2) protect the -NH2 group on 4, or 3) explore different basic conditions instead of using acetate.

<img width="700" alt="Screenshot 2024-01-31 at 10 14 15" src="https://github.com/OpenSourceMalaria/Series3/assets/102600515/73529bbf-4603-417a-9749-1000723d4198">

We are also running a new round of computational modelling on different 106 analogues and I will keep you updated.

Feel free to give any suggestion and let me know if you have any questions :)

**Comment by JamesAustinJA** [comment]
Hi @yinuowang0812 thanks for sending these targets through to me. I've found the route to the intermediate on the wiki page and I've added the image for that route below. I'll get some of the boronic acids in to do the final coupling or modify it for the thiol. I might trial some Diversinate chemistry to add the CF3 group in too. [1](https://pubs.acs.org/doi/10.1021/ja406223k)

<img width="1330" alt="OSM series 3 intermediate route" src="https://github.com/OpenSourceMalaria/Series3/assets/138777144/40049d31-4176-4d66-a668-62b508ae36f3">

How urgent is the work on screening for the Miyaura borylation conditions? As I mentioned I'm trying to help out a little bit throughout the year to get a grips with the project before our student starts in September. Towards the end of the year they would take over with a lot more synthesis and design. Here at Vertex we do have some preplated screening capabilities to look at various conditions for palladium couplings, catalysts, ligands and bases etc. That might be something we could help out with and would be a good exercise for them to undertake, however I understand if you need to look at that a lot sooner rather than waiting until the end of the year!

On some design ideas the above compounds would be great as a baseline but the free thiophene/furan are unlikley to make it as final drug compounds so changing them out for more drug-like rings might be more beneficial for future derivatives; thiazol/triazole/oxazole etc. Although this might be something to look at after there is data on these initial compounds. 

How difficult is it to get access to an online lab notebook? I would want to be able to update you all with my experimental data in real time - thanks for all your help with the background admin here! :)

**Comment by yinuowang0812** [comment]
Hi @JamesAustinJA , sorry for the late reply, I just came back from holiday.

Yes, it is the most commonly used synthetic route for the bromo-thienopyrimidine ring, which is followed by Suzuki coupling in the next step. I found that both the 3rd and 4th intermediates are commercially available and can be used in future iterations. The previous master's student attempted to add a CF3 group using the synthetic route below, but it resulted in a very low yield. The Baran Diversinates methods look very interesting and are worth trying.

<img width="400" alt="Screenshot 2024-02-22 at 11 55 16" src="https://github.com/OpenSourceMalaria/Series3/assets/102600515/76910a66-7522-4ba3-8ac7-df36852111af">

Our [latest paper](https://www.nature.com/articles/s41467-024-45224-z) and previous [wiki](https://github.com/OpenSourceMalaria/Series3/wiki/All-Analogs-Evaluated-to-Date) data have shown that even small changes to 106 can significantly impact the geometry of the binding site. So our current strategy is to focus on minor modifications to 106. I agree that thiazole, triazole, and oxazole are excellent targets, and maintaining minimal structural changes is crucial. It would be great if you and your student could also undertake their synthesis!

Thank you for the idea of Vertex's screening capabilities. I would appreciate it if you could run the screening if you have time. It opens up an additional synthetic route for creating new analogues, which is always beneficial. This could also help in the synthesis of the thiophene/thiazole molecules we mentioned, which provide more experience for the students when they join.

Do you want to create your own online lab notebook? We are using LabArchives, and I think you can create an ELN by being invited by @mattodd  if I remember correctly?

**Comment by mattodd** [comment]
Hi @JamesAustinJA - thank you for all this!

So, the borylation screen is indeed needed now. This is a curious little roadblock - if we can borylate the aminothienopyrimidine core (Br to boronate) then we could directly couple a bunch of quite expensive building blocks. But so far, it's not given us what we want. @yinuowang0812 - do you think you can write up a summary of all the reactions you've tried for this, with links to the relevant ELN pages as a new Issue?

Diversinate chem - we'd *love* to do any kind of late stage functionalisation work, yes, to maximise diversity without having to start the synthesis from scratch (we did a whole project on this a few years ago - one for a chat over a beer I suspect).

ELN - we can easily give you a guest pass to Labarchives, just say the word.

**Comment by JamesAustinJA** [comment]
Hi @mattodd, @yinuowang0812 it seems I was too hasty in trying to startup some collaboration. It looks like we won't be able to provide any help this year and may have to wait until the following year or potentially further. 

It seems getting these activities through our internal approval system is a lot more complex than we were hoping, so for the foreseeable future we won't be able to provide any synthetic help.

I however am adamant that this is an amazing initiative, and I will continue to push for some approval. I will continue to try to be active on here, even if I can't help practically, until this is all sorted on my end. 

Many thanks,
James

**Comment by yinuowang0812** [comment]
Hi @JamesAustinJA, we greatly appreciate your reaching out. We will continue to update the project here and look forward to hearing from you again :)
